### PR TITLE
Step2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by msmichellegar** [comment]
Do you mean to PR this to the main Node Girls workshop, or to your fork? We have a repo with the final solution which you're welcome to edit [here](https://github.com/node-girls/workshop-cms-complete) if you have any edits to make :)

PS looking forward to seeing you Saturday!

**Comment by ghost** [comment]
I meant to do it to my fork, and i've got absolutely no clue what i've done to make it no longer be in my fork...

**Comment by msmichellegar** [comment]
Ha. Maybe you cloned the main repo to your computer instead of your fork?

**Comment by msmichellegar** [comment]
If you want to reset the git url for your project, try `git remote set-url origin https://github.com/EmmaDeacon/workshop-cms.git`.

**Comment by ghost** [comment]
I was so sure i forked it and cloned from my fork. Sofia and I have no idea how it's come about this way.

**Comment by ghost** [comment]
Okay, thank you. :)

**Comment by ghost** [comment]
So does this now mean I am now working from my own fork? What on earth did I do!?

**Comment by msmichellegar** [comment]
You can check what the git url is set to by running `git remote -v`.

**Comment by msmichellegar** [comment]
If it's set to your own fork, then you should be good! Try pushing the commits again :)

**Comment by ghost** [comment]
I'm so so so sorry if i've completely screwed something up for you!

**Comment by ghost** [comment]
I've now got origin as https://github.com/EmmaDeacon/workshop-cms.git, so fingers crossed it won't happen again.

**Comment by msmichellegar** [comment]
No, it's all fine! So long as we don't merge the pull request, we're all good ;)

**Comment by msmichellegar** [comment]
Yay! Perfect. Want to close this pull request?

**Comment by ghost** [comment]
Yes yes, i'm so sorry again. I'll see you Saturday :) Do you know what time it is going to be?

**Comment by msmichellegar** [comment]
Ha, not a problem at all. It'll be 10-5 :)

**Pull request closed without merging**
