### PR TITLE
Fix git flow issues

### PR DESCRIPTION
**Pull request by claireinez**
When this is merged we can go ahead and delete all those redundant branches as well! :tada:

### CODE REVIEW

**Comment by claireinez** [comment]
Fixes https://github.com/node-girls/workshop-cms/issues/36 and https://github.com/node-girls/workshop-cms/issues/37.

**Review by msmichellegar — APPROVED** [review]

**Comment by msmichellegar** [comment]
Team effort.

**Comment by minaorangina** [comment]
☄️

**Comment by marisid** [comment]
Thanks girls :+1:

**Pull request merged**
